/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: [
        "introduction/introduction",
        "introduction/accessing-mel",
        "introduction/available-modules",
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: ["dashboard/about-dashboard", "dashboard/creating-dashboard"],
    },
    {
      type: "category",
      label: "Data entry",
      items: ["data-entry/data_entry_summary"],
    },
    {
      type: "category",
      label: "General Registration",
      items: ["general-registration/summary"],
    },
    {
      type: "category",
      label: "Reports",
      items: [
        "reports/summary",
        "reports/general_reports",
        "reports/standard_reports",
        "reports/uploaded_reports",
      ],
    },
    {
      type: "category",
      label: "Activity Tracker",
      items: ["activity-tracker/summary", "activity-tracker/creating-new"],
    },
    {
      type: "category",
      label: "User Management",
      items: ["user-management/summary"],
    },
    {
      type: "category",
      label: "MEL Library",
      items: ["resources/summary"],
    },
  ],
};
